; HERO.Z80
;
; Tile Source File.
;
; Info:
;   Section              : Tiles
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 16 x 16
;   Tiles                : 0 to 0
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

SECTION FRAGMENT "Tiles", ROM0

; Start of tile array.
Hero::
DB $00,$FF,$7F,$80,$7F,$80,$7F,$80
DB $7F,$80,$7F,$80,$7F,$BC,$7F,$80
DB $7F,$80,$7F,$83,$7F,$80,$7F,$80
DB $7F,$80,$7F,$80,$7F,$80,$00,$FF
DB $00,$FF,$FE,$01,$FE,$01,$FE,$01
DB $FE,$01,$FE,$01,$FE,$3D,$FE,$01
DB $FE,$01,$FE,$C1,$FE,$01,$FE,$01
DB $FE,$01,$FE,$01,$FE,$01,$00,$FF

; End of HERO.Z80
