; VILLAIN.Z80
;
; Tile Source File.
;
; Info:
;   Section              : Tiles
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 16 x 16
;   Tiles                : 0 to 0
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

SECTION FRAGMENT "Tiles", ROM0

; Start of tile array.
Villain::
DB $00,$FF,$7F,$80,$7F,$A0,$7F,$B0
DB $6F,$A8,$6F,$AC,$6B,$AA,$61,$A1
DB $7F,$9E,$7F,$80,$7F,$84,$7B,$8B
DB $7A,$9A,$78,$A8,$7F,$87,$00,$FF
DB $00,$FF,$FE,$01,$FE,$05,$FE,$0D
DB $F6,$15,$F6,$35,$D6,$55,$86,$85
DB $FE,$79,$FE,$01,$FE,$21,$DE,$D1
DB $5E,$59,$1E,$15,$FE,$E1,$00,$FF

; End of VILLAIN.Z80
